package alcoholmod.Mathioks.Final;

import alcoholmod.Mathioks.ExtendedPlayer;
import alcoholmod.Mathioks.block.Blockss;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import java.util.List;
import net.minecraft.block.Block;
import net.minecraft.entity.Entity;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.EnumRarity;
import net.minecraft.item.ItemStack;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.util.ChatComponentText;
import net.minecraft.util.EnumChatFormatting;
import net.minecraft.util.IChatComponent;
import net.minecraft.world.World;

public class KaguyaFinalDanceClematisFern extends JutsuItem {
  @SideOnly(Side.CLIENT)
  public EnumRarity getRarity(ItemStack par1ItemStack) {
    return EnumRarity.epic;
  }
  
  public void onUpdate(ItemStack par1ItemStack, World par2World, Entity par3Entity, int par4, boolean par5) {
    if ((EntityPlayer)par3Entity != null && par1ItemStack.stackTagCompound == null) {
      par1ItemStack.stackTagCompound = new NBTTagCompound();
      par1ItemStack.stackTagCompound.setString("Owner", ((EntityPlayer)par3Entity).getCommandSenderName());
    } 
  }
  
  public KaguyaFinalDanceClematisFern() {
    setMaxDamage(3700);
    this.maxStackSize = 1;
  }
  
  public ItemStack onItemRightClick(ItemStack Par1ItemStack, World Par2World, EntityPlayer Par3EntityPlayer) {
    if (!Par2World.isRemote)
      if (Par1ItemStack.stackTagCompound.getString("Owner").equals(Par3EntityPlayer.getCommandSenderName())) {
        ExtendedPlayer props = ExtendedPlayer.get(Par3EntityPlayer);
        if (props.getCurrentMana() >= 130 + props.getNinjutsu() / 600) {
          Par3EntityPlayer.addChatComponentMessage((IChatComponent)new ChatComponentText("Final Dance: Clematis Fern Destruction!!"));
          int i = (int)Par3EntityPlayer.posX;
          int j = (int)Par3EntityPlayer.posY;
          int k = (int)Par3EntityPlayer.posZ;
          Par2World.setBlock(i + 2, j + 5, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 4, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 3, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 2, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 1, k - 2, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 2, j, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 2, j - 1, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 5, j + 5, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 4, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 3, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 2, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 1, k - 2, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 5, j, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 5, j - 1, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j + 5, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 4, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 3, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 2, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 1, k - 2, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 8, j, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j - 1, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 13, j + 5, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 13, j + 4, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 13, j + 3, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 13, j + 2, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 13, j + 1, k - 2, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 13, j, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 13, j - 1, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 2, j + 5, k - 3, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 4, k - 3, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 3, k - 3, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 2, k - 3, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 1, k - 3, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 2, j, k - 3, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 2, j - 1, k - 3, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 2, j + 5, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 4, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 3, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 2, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 1, k - 5, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 2, j, k - 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 2, j - 1, k - 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 3, j + 5, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 3, j + 4, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 3, j + 3, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 3, j + 2, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 3, j + 1, k - 8, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 3, j, k - 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 3, j - 1, k - 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 2, j + 5, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 4, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 3, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 2, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 1, k - 12, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 2, j, k - 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 2, j - 1, k - 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 2, j + 5, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 4, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 3, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 2, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 1, k - 2, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 2, j, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 2, j - 1, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 4, j + 5, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 4, j + 4, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 4, j + 3, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 4, j + 2, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 4, j + 1, k - 2, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 4, j, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 4, j - 1, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 8, j + 5, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 4, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 3, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 2, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 1, k - 2, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 8, j, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 8, j - 1, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 12, j + 5, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 4, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 3, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 2, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 1, k - 2, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 12, j, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 12, j - 1, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 2, j + 5, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 4, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 3, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 2, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 1, k + 2, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 2, j, k + 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 2, j - 1, k + 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 3, j + 5, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 3, j + 4, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 3, j + 3, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 3, j + 2, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 3, j + 1, k + 5, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 3, j, k + 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 3, j - 1, k + 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 2, j + 5, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 4, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 3, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 2, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 1, k + 8, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 2, j, k + 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 2, j - 1, k + 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 2, j + 5, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 4, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 3, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 2, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 1, k + 12, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 2, j, k + 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 2, j - 1, k + 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 5, j + 5, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 4, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 3, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 2, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 1, k + 5, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 5, j, k + 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 5, j - 1, k + 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 7, j + 5, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 7, j + 4, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 7, j + 3, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 7, j + 2, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 7, j + 1, k + 5, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 7, j, k + 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 7, j - 1, k + 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 12, j + 5, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 4, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 3, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 2, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 1, k + 5, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 12, j, k + 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 12, j - 1, k + 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 5, j + 5, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 4, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 3, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 2, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 1, k + 2, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 5, j, k + 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 5, j - 1, k + 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j + 5, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 4, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 3, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 2, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 1, k + 2, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 8, j, k + 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j - 1, k + 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 11, j + 5, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 11, j + 4, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 11, j + 3, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 11, j + 2, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 11, j + 1, k + 2, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 11, j, k + 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 11, j - 1, k + 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 5, j + 5, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 4, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 3, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 2, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 1, k + 5, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 5, j, k + 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 5, j - 1, k + 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j + 5, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 4, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 3, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 2, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 1, k + 5, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 8, j, k + 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j - 1, k + 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 13, j + 5, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 13, j + 4, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 13, j + 3, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 13, j + 2, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 13, j + 1, k + 5, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 13, j, k + 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 13, j - 1, k + 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j + 5, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 4, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 3, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 2, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 1, k + 8, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 8, j, k + 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j - 1, k + 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 5, j + 5, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 4, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 3, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 2, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 1, k - 5, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 5, j, k - 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 5, j - 1, k - 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j + 5, k - 6, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 4, k - 6, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 3, k - 6, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 2, k - 6, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 1, k - 6, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 8, j, k - 6, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j - 1, k - 6, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 12, j + 5, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 4, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 3, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 2, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 1, k - 5, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 12, j, k - 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 12, j - 1, k - 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 5, j + 5, k - 9, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 4, k - 9, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 3, k - 9, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 2, k - 9, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 1, k - 9, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 5, j, k - 9, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 5, j - 1, k - 9, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j + 5, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 4, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 3, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 2, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 1, k - 8, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 8, j, k - 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j - 1, k - 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 12, j + 5, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 4, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 3, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 2, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 1, k - 8, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 12, j, k - 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 12, j - 1, k - 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 4, j + 5, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 4, j + 4, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 4, j + 3, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 4, j + 2, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 4, j + 1, k - 12, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 4, j, k - 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 4, j - 1, k - 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j + 5, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 4, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 3, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 2, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 1, k - 12, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 8, j, k - 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j - 1, k - 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 12, j + 5, k - 13, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 4, k - 13, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 3, k - 13, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 2, k - 13, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 1, k - 13, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 12, j, k - 13, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 12, j - 1, k - 13, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 5, j + 5, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 4, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 3, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 2, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 1, k - 5, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 5, j, k - 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 5, j - 1, k - 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 5, j + 5, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 4, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 3, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 2, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 1, k - 8, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 5, j, k - 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 5, j - 1, k - 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 6, j + 5, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 6, j + 4, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 6, j + 3, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 6, j + 2, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 6, j + 1, k - 12, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 6, j, k - 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 6, j - 1, k - 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j + 5, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 4, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 3, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 2, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 1, k - 5, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 8, j, k - 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j - 1, k - 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 9, j + 5, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 9, j + 4, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 9, j + 3, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 9, j + 2, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 9, j + 1, k - 8, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 9, j, k - 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 9, j - 1, k - 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j + 5, k - 11, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 4, k - 11, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 3, k - 11, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 2, k - 11, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 1, k - 11, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 8, j, k - 11, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j - 1, k - 11, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 12, j + 5, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 4, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 3, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 2, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 1, k - 5, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 12, j, k - 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 12, j - 1, k - 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 12, j + 5, k - 10, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 4, k - 10, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 3, k - 10, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 2, k - 10, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 1, k - 10, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 12, j, k - 10, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 12, j - 1, k - 10, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 12, j + 5, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 4, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 3, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 2, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 1, k - 12, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 12, j, k - 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 12, j - 1, k - 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j + 5, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 4, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 3, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 2, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 1, k + 8, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 8, j, k + 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j - 1, k + 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 12, j + 5, k + 9, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 4, k + 9, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 3, k + 9, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 2, k + 9, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 12, j + 1, k + 9, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 12, j, k + 9, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 12, j - 1, k + 9, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j + 5, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 4, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 3, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 2, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 1, k + 12, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 8, j, k + 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j - 1, k + 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 11, j + 5, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 11, j + 4, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 11, j + 3, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 11, j + 2, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 11, j + 1, k + 12, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 11, j, k + 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 11, j - 1, k + 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 12, j + 5, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 4, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 3, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 2, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 1, k - 8, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 12, j, k - 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 12, j - 1, k - 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 8, j + 5, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 4, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 3, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 2, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 1, k - 8, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 8, j, k - 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 8, j - 1, k - 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 12, j + 5, k - 13, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 4, k - 13, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 3, k - 13, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 2, k - 13, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 1, k - 13, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 12, j, k - 13, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 12, j - 1, k - 13, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 8, j + 5, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 4, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 3, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 2, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 1, k - 12, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 8, j, k - 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 8, j - 1, k - 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 6, j + 5, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 6, j + 4, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 6, j + 3, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 6, j + 2, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 6, j + 1, k - 8, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 6, j, k - 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 6, j - 1, k - 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 5, j + 5, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 4, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 3, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 2, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 1, k - 5, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 5, j, k - 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 5, j - 1, k - 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 5, j + 5, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 4, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 3, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 2, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 1, k - 12, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 5, j, k - 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 5, j - 1, k - 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 7, j + 5, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 7, j + 4, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 7, j + 3, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 7, j + 2, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 7, j + 1, k - 5, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 7, j, k - 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 7, j - 1, k - 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 12, j + 5, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 4, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 3, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 2, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 1, k - 5, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 12, j, k - 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 12, j - 1, k - 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 10, j + 5, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 10, j + 4, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 10, j + 3, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 10, j + 2, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 10, j + 1, k - 8, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 10, j, k - 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 10, j - 1, k - 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 6, j + 5, k - 7, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 6, j + 4, k - 7, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 6, j + 3, k - 7, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 6, j + 2, k - 7, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 6, j + 1, k - 7, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 6, j, k - 7, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 6, j - 1, k - 7, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 2, j + 5, k - 6, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 4, k - 6, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 3, k - 6, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 2, k - 6, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 1, k - 6, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 2, j, k - 6, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 2, j - 1, k - 6, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 3, j + 5, k - 6, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 3, j + 4, k - 6, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 3, j + 3, k - 6, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 3, j + 2, k - 6, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 3, j + 1, k - 6, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 3, j, k - 6, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 3, j - 1, k - 6, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 2, j + 5, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 4, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 3, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 2, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 1, k + 5, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 2, j, k + 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 2, j - 1, k + 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 2, j + 5, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 4, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 3, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 2, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 1, k + 8, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 2, j, k + 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 2, j - 1, k + 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 3, j + 5, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 3, j + 4, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 3, j + 3, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 3, j + 2, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 3, j + 1, k + 12, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 3, j, k + 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 3, j - 1, k + 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 5, j + 5, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 4, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 3, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 2, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 1, k + 5, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 5, j, k + 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 5, j - 1, k + 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 5, j + 5, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 4, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 3, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 2, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 1, k + 8, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 5, j, k + 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 5, j - 1, k + 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 6, j + 5, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 6, j + 4, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 6, j + 3, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 6, j + 2, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 6, j + 1, k + 12, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 6, j, k + 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 6, j - 1, k + 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 8, j + 5, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 4, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 3, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 2, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 1, k + 5, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 8, j, k + 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 8, j - 1, k + 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 8, j + 5, k + 9, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 4, k + 9, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 3, k + 9, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 2, k + 9, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 1, k + 9, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 8, j, k + 9, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 8, j - 1, k + 9, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 8, j + 5, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 4, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 3, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 2, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 1, k + 12, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 8, j, k + 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 8, j - 1, k + 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 12, j + 5, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 4, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 3, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 2, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 1, k + 12, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 12, j, k + 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 12, j - 1, k + 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 9, j + 5, k + 4, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 9, j + 4, k + 4, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 9, j + 3, k + 4, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 9, j + 2, k + 4, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 9, j + 1, k + 4, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 9, j, k + 4, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 9, j - 1, k + 4, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 13, j + 5, k - 6, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 13, j + 4, k - 6, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 13, j + 3, k - 6, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 13, j + 2, k - 6, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 13, j + 1, k - 6, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 13, j, k - 6, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 13, j - 1, k - 6, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 5, j + 5, k + 7, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 4, k + 7, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 3, k + 7, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 2, k + 7, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 1, k + 7, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 5, j, k + 7, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 5, j - 1, k + 7, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 3, j + 5, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 3, j + 4, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 3, j + 3, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 3, j + 2, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 3, j + 1, k + 2, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 3, j, k + 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 3, j - 1, k + 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 6, j + 5, k + 13, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 6, j + 4, k + 13, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 6, j + 3, k + 13, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 6, j + 2, k + 13, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 6, j + 1, k + 13, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 6, j, k + 13, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 6, j - 1, k + 13, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j + 5, k - 4, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 4, k - 4, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 3, k - 4, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 2, k - 4, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 1, k - 4, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 8, j, k - 4, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j - 1, k - 4, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 5, j + 5, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 4, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 3, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 2, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 1, k + 8, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 5, j, k + 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 5, j - 1, k + 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 6, j + 5, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 6, j + 4, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 6, j + 3, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 6, j + 2, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 6, j + 1, k + 12, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 6, j, k + 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 6, j - 1, k + 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 2, j + 5, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 4, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 3, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 2, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 2, j + 1, k + 8, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 2, j, k + 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 2, j - 1, k + 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 3, j + 5, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 3, j + 4, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 3, j + 3, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 3, j + 2, k + 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 3, j + 1, k + 12, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 3, j, k + 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 3, j - 1, k + 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 12, j + 5, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 4, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 3, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 2, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 1, k + 8, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 12, j, k + 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 12, j - 1, k + 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i, j + 5, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 4, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 3, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 2, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 1, k - 5, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i, j, k - 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i, j - 1, k - 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i, j + 5, k - 9, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 4, k - 9, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 3, k - 9, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 2, k - 9, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 1, k - 9, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i, j, k - 9, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i, j - 1, k - 9, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i, j + 5, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 4, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 3, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 2, k - 12, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 1, k - 12, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i, j, k - 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i, j - 1, k - 12, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 4, j + 5, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 4, j + 4, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 4, j + 3, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 4, j + 2, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 4, j + 1, k, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 4, j, k, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 4, j - 1, k, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 8, j + 5, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 4, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 3, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 2, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 1, k, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 8, j, k, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 8, j - 1, k, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 12, j + 5, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 4, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 3, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 2, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 1, k, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 12, j, k, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 12, j - 1, k, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 2, j + 5, k - 11, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 4, k - 11, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 3, k - 11, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 2, k - 11, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 1, k - 11, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 2, j, k - 11, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 2, j - 1, k - 11, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 2, j + 5, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 4, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 3, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 2, k - 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 1, k - 8, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 2, j, k - 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 2, j - 1, k - 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 2, j + 5, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 4, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 3, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 2, k - 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 1, k - 5, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 2, j, k - 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 2, j - 1, k - 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 3, j + 5, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 3, j + 4, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 3, j + 3, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 3, j + 2, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 3, j + 1, k - 2, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 3, j, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 3, j - 1, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 5, j + 5, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 4, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 3, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 2, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 1, k - 2, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 5, j, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 5, j - 1, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 8, j + 5, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 4, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 3, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 2, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 8, j + 1, k - 2, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 8, j, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 8, j - 1, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 12, j + 5, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 4, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 3, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 2, k - 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 1, k - 2, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 12, j, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 12, j - 1, k - 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i, j + 5, k + 11, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 4, k + 11, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 3, k + 11, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 2, k + 11, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 1, k + 11, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i, j, k + 11, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i, j - 1, k + 11, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i, j + 5, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 4, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 3, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 2, k + 8, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 1, k + 8, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i, j, k + 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i, j - 1, k + 8, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i, j + 5, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 4, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 3, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 2, k + 5, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i, j + 1, k + 5, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i, j, k + 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i, j - 1, k + 5, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 5, j + 5, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 4, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 3, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 2, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 1, k, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 5, j, k, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 5, j - 1, k, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j + 5, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 4, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 3, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 2, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 8, j + 1, k, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 8, j, k, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 8, j - 1, k, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 5, j + 5, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 4, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 3, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 2, k, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i + 5, j + 1, k, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i + 5, j, k, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i + 5, j - 1, k, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 2, j + 5, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 4, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 3, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 2, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 2, j + 1, k + 2, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 2, j, k + 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 2, j - 1, k + 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 5, j + 5, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 4, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 3, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 2, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 5, j + 1, k + 2, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 5, j, k + 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 5, j - 1, k + 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 9, j + 5, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 9, j + 4, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 9, j + 3, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 9, j + 2, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 9, j + 1, k + 2, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 9, j, k + 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 9, j - 1, k + 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 12, j + 5, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 4, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 3, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 2, k + 2, (Block)Blockss.blockBoneTop);
          Par2World.setBlock(i - 12, j + 1, k + 2, (Block)Blockss.blockBoneDown);
          Par2World.setBlock(i - 12, j, k + 2, (Block)Blockss.blockBoneLowest);
          Par2World.setBlock(i - 12, j - 1, k + 2, (Block)Blockss.blockBoneLowest);
          props.consumeMana(130 + props.getNinjutsu() / 600);
        } else {
          Par3EntityPlayer.addChatComponentMessage((IChatComponent)new ChatComponentText("You do not have enough chakra!"));
        } 
      } else {
        Par3EntityPlayer.addChatComponentMessage((IChatComponent)new ChatComponentText("You are not the owner of this jutsu"));
      }  
    return Par1ItemStack;
  }
  
  @SideOnly(Side.CLIENT)
  public void addInformation(ItemStack par1ItemStack, EntityPlayer par2EntityPlayer, List par3List, boolean par4) {
    ExtendedPlayer props = ExtendedPlayer.get(par2EntityPlayer);
    if (par1ItemStack.stackTagCompound != null)
      par3List.add(EnumChatFormatting.AQUA + "Owner: " + par1ItemStack.stackTagCompound.getString("Owner")); 
    par3List.add(EnumChatFormatting.DARK_AQUA + "The ultimate Shikotsumyaku skill,");
    par3List.add(EnumChatFormatting.DARK_AQUA + "Turns the field into a bone area");
    par3List.add(EnumChatFormatting.GOLD + "Chakra Cost: " + (130 + props.getNinjutsu() / 600));
  }
}
