package alcoholmod.Mathioks.Final;

import alcoholmod.Mathioks.ExtendedPlayer;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import java.util.List;
import net.minecraft.block.Block;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.init.Blocks;
import net.minecraft.item.EnumRarity;
import net.minecraft.item.ItemStack;
import net.minecraft.util.ChatComponentText;
import net.minecraft.util.EnumChatFormatting;
import net.minecraft.util.IChatComponent;
import net.minecraft.world.World;

public class SandReleaseSandTsunami extends JutsuItem {
  @SideOnly(Side.CLIENT)
  public EnumRarity getRarity(ItemStack par1ItemStack) {
    return EnumRarity.epic;
  }
  
  public SandReleaseSandTsunami() {
    setMaxDamage(3700);
    this.maxStackSize = 1;
  }
  
  public ItemStack onItemRightClick(ItemStack Par1ItemStack, World Par2World, EntityPlayer Par3EntityPlayer) {
    if (!Par2World.isRemote) {
      ExtendedPlayer props = ExtendedPlayer.get(Par3EntityPlayer);
      if (props.getCurrentMana() >= 25 + props.getNinjutsu() / 600) {
        int i = (int)Par3EntityPlayer.posX;
        int j = (int)Par3EntityPlayer.posY;
        int k = (int)Par3EntityPlayer.posZ;
        Par2World.setBlock(i + 5, j + 2, k - 5, Blocks.air);
        Par2World.setBlock(i + 5, j + 2, k - 4, Blocks.air);
        Par2World.setBlock(i + 5, j + 2, k - 3, Blocks.air);
        Par2World.setBlock(i + 5, j + 2, k - 2, Blocks.air);
        Par2World.setBlock(i + 5, j + 2, k - 1, Blocks.air);
        Par2World.setBlock(i + 5, j + 2, k, Blocks.air);
        Par2World.setBlock(i + 5, j + 2, k + 1, Blocks.air);
        Par2World.setBlock(i + 5, j + 2, k + 2, Blocks.air);
        Par2World.setBlock(i + 5, j + 2, k + 3, Blocks.air);
        Par2World.setBlock(i + 5, j + 2, k + 4, Blocks.air);
        Par2World.setBlock(i + 5, j + 2, k + 5, Blocks.air);
        Par2World.setBlock(i - 5, j + 2, k - 5, Blocks.air);
        Par2World.setBlock(i - 5, j + 2, k - 4, Blocks.air);
        Par2World.setBlock(i - 5, j + 2, k - 3, Blocks.air);
        Par2World.setBlock(i - 5, j + 2, k - 2, Blocks.air);
        Par2World.setBlock(i - 5, j + 2, k - 1, Blocks.air);
        Par2World.setBlock(i - 5, j + 2, k, Blocks.air);
        Par2World.setBlock(i - 5, j + 2, k + 1, Blocks.air);
        Par2World.setBlock(i - 5, j + 2, k + 2, Blocks.air);
        Par2World.setBlock(i - 5, j + 2, k + 3, Blocks.air);
        Par2World.setBlock(i - 5, j + 2, k + 4, Blocks.air);
        Par2World.setBlock(i - 5, j + 2, k + 5, Blocks.air);
        Par2World.setBlock(i - 4, j + 2, k + 5, Blocks.air);
        Par2World.setBlock(i - 3, j + 2, k + 5, Blocks.air);
        Par2World.setBlock(i - 2, j + 2, k + 5, Blocks.air);
        Par2World.setBlock(i - 1, j + 2, k + 5, Blocks.air);
        Par2World.setBlock(i, j + 2, k + 5, Blocks.air);
        Par2World.setBlock(i + 1, j + 2, k + 5, Blocks.air);
        Par2World.setBlock(i + 2, j + 2, k + 5, Blocks.air);
        Par2World.setBlock(i + 3, j + 2, k + 5, Blocks.air);
        Par2World.setBlock(i - 4, j + 2, k + 5, Blocks.air);
        Par2World.setBlock(i - 4, j + 2, k - 5, Blocks.air);
        Par2World.setBlock(i - 3, j + 2, k - 5, Blocks.air);
        Par2World.setBlock(i - 2, j + 2, k - 5, Blocks.air);
        Par2World.setBlock(i - 1, j + 2, k - 5, Blocks.air);
        Par2World.setBlock(i, j + 2, k - 5, Blocks.air);
        Par2World.setBlock(i + 1, j + 2, k - 5, Blocks.air);
        Par2World.setBlock(i + 2, j + 2, k - 5, Blocks.air);
        Par2World.setBlock(i + 3, j + 2, k - 5, Blocks.air);
        Par2World.setBlock(i - 4, j + 2, k - 5, Blocks.air);
        Par2World.setBlock(i + 4, j + 1, k - 4, Blocks.air);
        Par2World.setBlock(i + 4, j + 1, k - 3, Blocks.air);
        Par2World.setBlock(i + 4, j + 1, k - 2, Blocks.air);
        Par2World.setBlock(i + 4, j + 1, k - 1, Blocks.air);
        Par2World.setBlock(i + 4, j + 1, k, Blocks.air);
        Par2World.setBlock(i + 4, j + 1, k + 1, Blocks.air);
        Par2World.setBlock(i + 4, j + 1, k + 2, Blocks.air);
        Par2World.setBlock(i + 4, j + 1, k + 3, Blocks.air);
        Par2World.setBlock(i + 4, j + 1, k + 4, Blocks.air);
        Par2World.setBlock(i - 4, j + 1, k - 4, Blocks.air);
        Par2World.setBlock(i - 4, j + 1, k - 3, Blocks.air);
        Par2World.setBlock(i - 4, j + 1, k - 2, Blocks.air);
        Par2World.setBlock(i - 4, j + 1, k - 1, Blocks.air);
        Par2World.setBlock(i - 4, j + 1, k, Blocks.air);
        Par2World.setBlock(i - 4, j + 1, k + 1, Blocks.air);
        Par2World.setBlock(i - 4, j + 1, k + 2, Blocks.air);
        Par2World.setBlock(i - 4, j + 1, k + 3, Blocks.air);
        Par2World.setBlock(i - 4, j + 1, k + 4, Blocks.air);
        Par2World.setBlock(i - 3, j + 1, k + 4, Blocks.air);
        Par2World.setBlock(i - 2, j + 1, k + 4, Blocks.air);
        Par2World.setBlock(i - 1, j + 1, k + 4, Blocks.air);
        Par2World.setBlock(i, j + 1, k + 4, Blocks.air);
        Par2World.setBlock(i + 1, j + 1, k + 4, Blocks.air);
        Par2World.setBlock(i + 2, j + 1, k + 4, Blocks.air);
        Par2World.setBlock(i + 3, j + 1, k + 4, Blocks.air);
        Par2World.setBlock(i - 3, j + 1, k - 4, Blocks.air);
        Par2World.setBlock(i - 2, j + 1, k - 4, Blocks.air);
        Par2World.setBlock(i - 1, j + 1, k - 4, Blocks.air);
        Par2World.setBlock(i, j + 1, k - 4, Blocks.air);
        Par2World.setBlock(i + 1, j + 1, k - 4, Blocks.air);
        Par2World.setBlock(i + 2, j + 1, k - 4, Blocks.air);
        Par2World.setBlock(i + 3, j + 1, k - 4, Blocks.air);
        Par2World.setBlock(i + 5, j + 1, k - 5, Blocks.air);
        Par2World.setBlock(i + 5, j + 1, k - 4, Blocks.air);
        Par2World.setBlock(i + 5, j + 1, k - 3, Blocks.air);
        Par2World.setBlock(i + 5, j + 1, k - 2, Blocks.air);
        Par2World.setBlock(i + 5, j + 1, k - 1, Blocks.air);
        Par2World.setBlock(i + 5, j + 1, k, Blocks.air);
        Par2World.setBlock(i + 5, j + 1, k + 1, Blocks.air);
        Par2World.setBlock(i + 5, j + 1, k + 2, Blocks.air);
        Par2World.setBlock(i + 5, j + 1, k + 3, Blocks.air);
        Par2World.setBlock(i + 5, j + 1, k + 4, Blocks.air);
        Par2World.setBlock(i + 5, j + 1, k + 5, Blocks.air);
        Par2World.setBlock(i - 5, j + 1, k - 5, Blocks.air);
        Par2World.setBlock(i - 5, j + 1, k - 4, Blocks.air);
        Par2World.setBlock(i - 5, j + 1, k - 3, Blocks.air);
        Par2World.setBlock(i - 5, j + 1, k - 2, Blocks.air);
        Par2World.setBlock(i - 5, j + 1, k - 1, Blocks.air);
        Par2World.setBlock(i - 5, j + 1, k, Blocks.air);
        Par2World.setBlock(i - 5, j + 1, k + 1, Blocks.air);
        Par2World.setBlock(i - 5, j + 1, k + 2, Blocks.air);
        Par2World.setBlock(i - 5, j + 1, k + 3, Blocks.air);
        Par2World.setBlock(i - 5, j + 1, k + 4, Blocks.air);
        Par2World.setBlock(i - 5, j + 1, k + 5, Blocks.air);
        Par2World.setBlock(i - 4, j + 1, k + 5, Blocks.air);
        Par2World.setBlock(i - 3, j + 1, k + 5, Blocks.air);
        Par2World.setBlock(i - 2, j + 1, k + 5, Blocks.air);
        Par2World.setBlock(i - 1, j + 1, k + 5, Blocks.air);
        Par2World.setBlock(i, j + 1, k + 5, Blocks.air);
        Par2World.setBlock(i + 1, j + 1, k + 5, Blocks.air);
        Par2World.setBlock(i + 2, j + 1, k + 5, Blocks.air);
        Par2World.setBlock(i + 3, j + 1, k + 5, Blocks.air);
        Par2World.setBlock(i - 4, j + 1, k + 5, Blocks.air);
        Par2World.setBlock(i - 4, j + 1, k - 5, Blocks.air);
        Par2World.setBlock(i - 3, j + 1, k - 5, Blocks.air);
        Par2World.setBlock(i - 2, j + 1, k - 5, Blocks.air);
        Par2World.setBlock(i - 1, j + 1, k - 5, Blocks.air);
        Par2World.setBlock(i, j + 1, k - 5, Blocks.air);
        Par2World.setBlock(i + 1, j + 1, k - 5, Blocks.air);
        Par2World.setBlock(i + 2, j + 1, k - 5, Blocks.air);
        Par2World.setBlock(i + 3, j + 1, k - 5, Blocks.air);
        Par2World.setBlock(i - 4, j + 1, k - 5, Blocks.air);
        Par2World.setBlock(i - 3, j, k + 3, Blocks.air);
        Par2World.setBlock(i - 3, j, k + 2, Blocks.air);
        Par2World.setBlock(i - 3, j, k + 1, Blocks.air);
        Par2World.setBlock(i - 3, j, k, Blocks.air);
        Par2World.setBlock(i - 3, j, k - 1, Blocks.air);
        Par2World.setBlock(i - 3, j, k - 2, Blocks.air);
        Par2World.setBlock(i - 3, j, k - 3, Blocks.air);
        Par2World.setBlock(i - 2, j, k + 3, Blocks.air);
        Par2World.setBlock(i - 2, j, k - 3, Blocks.air);
        Par2World.setBlock(i - 1, j, k + 3, Blocks.air);
        Par2World.setBlock(i - 1, j, k - 3, Blocks.air);
        Par2World.setBlock(i, j, k + 3, Blocks.air);
        Par2World.setBlock(i, j, k - 3, Blocks.air);
        Par2World.setBlock(i + 1, j, k + 3, Blocks.air);
        Par2World.setBlock(i + 1, j, k - 3, Blocks.air);
        Par2World.setBlock(i + 2, j, k + 3, Blocks.air);
        Par2World.setBlock(i + 2, j, k - 2, Blocks.air);
        Par2World.setBlock(i + 2, j, k - 3, Blocks.air);
        Par2World.setBlock(i + 3, j, k + 3, Blocks.air);
        Par2World.setBlock(i + 3, j, k + 2, Blocks.air);
        Par2World.setBlock(i + 3, j, k + 1, Blocks.air);
        Par2World.setBlock(i + 3, j, k, Blocks.air);
        Par2World.setBlock(i + 3, j, k - 1, Blocks.air);
        Par2World.setBlock(i + 3, j, k - 2, Blocks.air);
        Par2World.setBlock(i + 3, j, k - 3, Blocks.air);
        Par2World.setBlock(i + 4, j, k - 4, Blocks.air);
        Par2World.setBlock(i + 4, j, k - 3, Blocks.air);
        Par2World.setBlock(i + 4, j, k - 2, Blocks.air);
        Par2World.setBlock(i + 4, j, k - 1, Blocks.air);
        Par2World.setBlock(i + 4, j, k, Blocks.air);
        Par2World.setBlock(i + 4, j, k + 1, Blocks.air);
        Par2World.setBlock(i + 4, j, k + 2, Blocks.air);
        Par2World.setBlock(i + 4, j, k + 3, Blocks.air);
        Par2World.setBlock(i + 4, j, k + 4, Blocks.air);
        Par2World.setBlock(i - 4, j, k - 4, Blocks.air);
        Par2World.setBlock(i - 4, j, k - 3, Blocks.air);
        Par2World.setBlock(i - 4, j, k - 2, Blocks.air);
        Par2World.setBlock(i - 4, j, k - 1, Blocks.air);
        Par2World.setBlock(i - 4, j, k, Blocks.air);
        Par2World.setBlock(i - 4, j, k + 1, Blocks.air);
        Par2World.setBlock(i - 4, j, k + 2, Blocks.air);
        Par2World.setBlock(i - 4, j, k + 3, Blocks.air);
        Par2World.setBlock(i - 4, j, k + 4, Blocks.air);
        Par2World.setBlock(i - 3, j, k + 4, Blocks.air);
        Par2World.setBlock(i - 2, j, k + 4, Blocks.air);
        Par2World.setBlock(i - 1, j, k + 4, Blocks.air);
        Par2World.setBlock(i, j, k + 4, Blocks.air);
        Par2World.setBlock(i + 1, j, k + 4, Blocks.air);
        Par2World.setBlock(i + 2, j, k + 4, Blocks.air);
        Par2World.setBlock(i + 3, j, k + 4, Blocks.air);
        Par2World.setBlock(i - 3, j, k - 4, Blocks.air);
        Par2World.setBlock(i - 2, j, k - 4, Blocks.air);
        Par2World.setBlock(i - 1, j, k - 4, Blocks.air);
        Par2World.setBlock(i, j, k - 4, Blocks.air);
        Par2World.setBlock(i + 1, j, k - 4, Blocks.air);
        Par2World.setBlock(i + 2, j, k - 4, Blocks.air);
        Par2World.setBlock(i + 3, j, k - 4, Blocks.air);
        Par2World.setBlock(i + 5, j, k - 5, Blocks.air);
        Par2World.setBlock(i + 5, j, k - 4, Blocks.air);
        Par2World.setBlock(i + 5, j, k - 3, Blocks.air);
        Par2World.setBlock(i + 5, j, k - 2, Blocks.air);
        Par2World.setBlock(i + 5, j, k - 1, Blocks.air);
        Par2World.setBlock(i + 5, j, k, Blocks.air);
        Par2World.setBlock(i + 5, j, k + 1, Blocks.air);
        Par2World.setBlock(i + 5, j, k + 2, Blocks.air);
        Par2World.setBlock(i + 5, j, k + 3, Blocks.air);
        Par2World.setBlock(i + 5, j, k + 4, Blocks.air);
        Par2World.setBlock(i + 5, j, k + 5, Blocks.air);
        Par2World.setBlock(i - 5, j, k - 5, Blocks.air);
        Par2World.setBlock(i - 5, j, k - 4, Blocks.air);
        Par2World.setBlock(i - 5, j, k - 3, Blocks.air);
        Par2World.setBlock(i - 5, j, k - 2, Blocks.air);
        Par2World.setBlock(i - 5, j, k - 1, Blocks.air);
        Par2World.setBlock(i - 5, j, k, Blocks.air);
        Par2World.setBlock(i - 5, j, k + 1, Blocks.air);
        Par2World.setBlock(i - 5, j, k + 2, Blocks.air);
        Par2World.setBlock(i - 5, j, k + 3, Blocks.air);
        Par2World.setBlock(i - 5, j, k + 4, Blocks.air);
        Par2World.setBlock(i - 5, j, k + 5, Blocks.air);
        Par2World.setBlock(i - 4, j, k + 5, Blocks.air);
        Par2World.setBlock(i - 3, j, k + 5, Blocks.air);
        Par2World.setBlock(i - 2, j, k + 5, Blocks.air);
        Par2World.setBlock(i - 1, j, k + 5, Blocks.air);
        Par2World.setBlock(i, j, k + 5, Blocks.air);
        Par2World.setBlock(i + 1, j, k + 5, Blocks.air);
        Par2World.setBlock(i + 2, j, k + 5, Blocks.air);
        Par2World.setBlock(i + 3, j, k + 5, Blocks.air);
        Par2World.setBlock(i - 4, j, k + 5, Blocks.air);
        Par2World.setBlock(i - 4, j, k - 5, Blocks.air);
        Par2World.setBlock(i - 3, j, k - 5, Blocks.air);
        Par2World.setBlock(i - 2, j, k - 5, Blocks.air);
        Par2World.setBlock(i - 1, j, k - 5, Blocks.air);
        Par2World.setBlock(i, j, k - 5, Blocks.air);
        Par2World.setBlock(i + 1, j, k - 5, Blocks.air);
        Par2World.setBlock(i + 2, j, k - 5, Blocks.air);
        Par2World.setBlock(i + 3, j, k - 5, Blocks.air);
        Par2World.setBlock(i - 4, j, k - 5, Blocks.air);
        Par2World.setBlock(i - 3, j - 1, k + 3, Blocks.air);
        Par2World.setBlock(i - 3, j - 1, k + 2, Blocks.air);
        Par2World.setBlock(i - 3, j - 1, k + 1, Blocks.air);
        Par2World.setBlock(i - 3, j - 1, k, Blocks.air);
        Par2World.setBlock(i - 3, j - 1, k - 1, Blocks.air);
        Par2World.setBlock(i - 3, j - 1, k - 2, Blocks.air);
        Par2World.setBlock(i - 3, j - 1, k - 3, Blocks.air);
        Par2World.setBlock(i - 2, j - 1, k + 3, Blocks.air);
        Par2World.setBlock(i - 2, j - 1, k + 2, Blocks.air);
        Par2World.setBlock(i - 2, j - 1, k + 1, Blocks.air);
        Par2World.setBlock(i - 2, j - 1, k, Blocks.air);
        Par2World.setBlock(i - 2, j - 1, k - 1, Blocks.air);
        Par2World.setBlock(i - 2, j - 1, k - 2, Blocks.air);
        Par2World.setBlock(i - 2, j - 1, k - 3, Blocks.air);
        Par2World.setBlock(i - 1, j - 1, k + 3, Blocks.air);
        Par2World.setBlock(i - 1, j - 1, k + 2, Blocks.air);
        Par2World.setBlock(i - 1, j - 1, k - 2, Blocks.air);
        Par2World.setBlock(i - 1, j - 1, k - 3, Blocks.air);
        Par2World.setBlock(i, j - 1, k + 3, Blocks.air);
        Par2World.setBlock(i, j - 1, k + 2, Blocks.air);
        Par2World.setBlock(i, j - 1, k - 2, Blocks.air);
        Par2World.setBlock(i, j - 1, k - 3, Blocks.air);
        Par2World.setBlock(i + 1, j - 1, k + 3, Blocks.air);
        Par2World.setBlock(i + 1, j - 1, k + 2, Blocks.air);
        Par2World.setBlock(i + 1, j - 1, k - 2, Blocks.air);
        Par2World.setBlock(i + 1, j - 1, k - 3, Blocks.air);
        Par2World.setBlock(i + 2, j - 1, k + 3, Blocks.air);
        Par2World.setBlock(i + 2, j - 1, k + 2, Blocks.air);
        Par2World.setBlock(i + 2, j - 1, k + 1, Blocks.air);
        Par2World.setBlock(i + 2, j - 1, k, Blocks.air);
        Par2World.setBlock(i + 2, j - 1, k - 1, Blocks.air);
        Par2World.setBlock(i + 2, j - 1, k - 2, Blocks.air);
        Par2World.setBlock(i + 2, j - 1, k - 3, Blocks.air);
        Par2World.setBlock(i + 3, j - 1, k + 3, Blocks.air);
        Par2World.setBlock(i + 3, j - 1, k + 2, Blocks.air);
        Par2World.setBlock(i + 3, j - 1, k + 1, Blocks.air);
        Par2World.setBlock(i + 3, j - 1, k, Blocks.air);
        Par2World.setBlock(i + 3, j - 1, k - 1, Blocks.air);
        Par2World.setBlock(i + 3, j - 1, k - 2, Blocks.air);
        Par2World.setBlock(i + 3, j - 1, k - 3, Blocks.air);
        Par2World.setBlock(i + 4, j - 1, k - 4, Blocks.air);
        Par2World.setBlock(i + 4, j - 1, k - 3, Blocks.air);
        Par2World.setBlock(i + 4, j - 1, k - 2, Blocks.air);
        Par2World.setBlock(i + 4, j - 1, k - 1, Blocks.air);
        Par2World.setBlock(i + 4, j - 1, k, Blocks.air);
        Par2World.setBlock(i + 4, j - 1, k + 1, Blocks.air);
        Par2World.setBlock(i + 4, j - 1, k + 2, Blocks.air);
        Par2World.setBlock(i + 4, j - 1, k + 3, Blocks.air);
        Par2World.setBlock(i + 4, j - 1, k + 4, Blocks.air);
        Par2World.setBlock(i - 4, j - 1, k - 4, Blocks.air);
        Par2World.setBlock(i - 4, j - 1, k - 3, Blocks.air);
        Par2World.setBlock(i - 4, j - 1, k - 2, Blocks.air);
        Par2World.setBlock(i - 4, j - 1, k - 1, Blocks.air);
        Par2World.setBlock(i - 4, j - 1, k, Blocks.air);
        Par2World.setBlock(i - 4, j - 1, k + 1, Blocks.air);
        Par2World.setBlock(i - 4, j - 1, k + 2, Blocks.air);
        Par2World.setBlock(i - 4, j - 1, k + 3, Blocks.air);
        Par2World.setBlock(i - 4, j - 1, k + 4, Blocks.air);
        Par2World.setBlock(i - 3, j - 1, k + 4, Blocks.air);
        Par2World.setBlock(i - 2, j - 1, k + 4, Blocks.air);
        Par2World.setBlock(i - 1, j - 1, k + 4, Blocks.air);
        Par2World.setBlock(i, j - 1, k + 4, Blocks.air);
        Par2World.setBlock(i + 1, j - 1, k + 4, Blocks.air);
        Par2World.setBlock(i + 2, j - 1, k + 4, Blocks.air);
        Par2World.setBlock(i + 3, j - 1, k + 4, Blocks.air);
        Par2World.setBlock(i - 3, j - 1, k - 4, Blocks.air);
        Par2World.setBlock(i - 2, j - 1, k - 4, Blocks.air);
        Par2World.setBlock(i - 1, j - 1, k - 4, Blocks.air);
        Par2World.setBlock(i, j - 1, k - 4, Blocks.air);
        Par2World.setBlock(i + 1, j - 1, k - 4, Blocks.air);
        Par2World.setBlock(i + 2, j - 1, k - 4, Blocks.air);
        Par2World.setBlock(i + 3, j - 1, k - 4, Blocks.air);
        Par2World.setBlock(i + 5, j - 1, k - 5, Blocks.air);
        Par2World.setBlock(i + 5, j - 1, k - 4, Blocks.air);
        Par2World.setBlock(i + 5, j - 1, k - 3, Blocks.air);
        Par2World.setBlock(i + 5, j - 1, k - 2, Blocks.air);
        Par2World.setBlock(i + 5, j - 1, k - 1, Blocks.air);
        Par2World.setBlock(i + 5, j - 1, k, Blocks.air);
        Par2World.setBlock(i + 5, j - 1, k + 1, Blocks.air);
        Par2World.setBlock(i + 5, j - 1, k + 2, Blocks.air);
        Par2World.setBlock(i + 5, j - 1, k + 3, Blocks.air);
        Par2World.setBlock(i + 5, j - 1, k + 4, Blocks.air);
        Par2World.setBlock(i + 5, j - 1, k + 5, Blocks.air);
        Par2World.setBlock(i - 5, j - 1, k - 5, Blocks.air);
        Par2World.setBlock(i - 5, j - 1, k - 4, Blocks.air);
        Par2World.setBlock(i - 5, j - 1, k - 3, Blocks.air);
        Par2World.setBlock(i - 5, j - 1, k - 2, Blocks.air);
        Par2World.setBlock(i - 5, j - 1, k - 1, Blocks.air);
        Par2World.setBlock(i - 5, j - 1, k, Blocks.air);
        Par2World.setBlock(i - 5, j - 1, k + 1, Blocks.air);
        Par2World.setBlock(i - 5, j - 1, k + 2, Blocks.air);
        Par2World.setBlock(i - 5, j - 1, k + 3, Blocks.air);
        Par2World.setBlock(i - 5, j - 1, k + 4, Blocks.air);
        Par2World.setBlock(i - 5, j - 1, k + 5, Blocks.air);
        Par2World.setBlock(i - 4, j - 1, k + 5, Blocks.air);
        Par2World.setBlock(i - 3, j - 1, k + 5, Blocks.air);
        Par2World.setBlock(i - 2, j - 1, k + 5, Blocks.air);
        Par2World.setBlock(i - 1, j - 1, k + 5, Blocks.air);
        Par2World.setBlock(i, j - 1, k + 5, Blocks.air);
        Par2World.setBlock(i + 1, j - 1, k + 5, Blocks.air);
        Par2World.setBlock(i + 2, j - 1, k + 5, Blocks.air);
        Par2World.setBlock(i + 3, j - 1, k + 5, Blocks.air);
        Par2World.setBlock(i - 4, j - 1, k + 5, Blocks.air);
        Par2World.setBlock(i - 4, j - 1, k - 5, Blocks.air);
        Par2World.setBlock(i - 3, j - 1, k - 5, Blocks.air);
        Par2World.setBlock(i - 2, j - 1, k - 5, Blocks.air);
        Par2World.setBlock(i - 1, j - 1, k - 5, Blocks.air);
        Par2World.setBlock(i, j - 1, k - 5, Blocks.air);
        Par2World.setBlock(i + 1, j - 1, k - 5, Blocks.air);
        Par2World.setBlock(i + 2, j - 1, k - 5, Blocks.air);
        Par2World.setBlock(i + 3, j - 1, k - 5, Blocks.air);
        Par2World.setBlock(i - 4, j - 1, k - 5, Blocks.air);
        Par2World.setBlock(i - 3, j - 2, k + 3, Blocks.air);
        Par2World.setBlock(i - 3, j - 2, k + 2, Blocks.air);
        Par2World.setBlock(i - 3, j - 2, k + 1, Blocks.air);
        Par2World.setBlock(i - 3, j - 2, k, Blocks.air);
        Par2World.setBlock(i - 3, j - 2, k - 1, Blocks.air);
        Par2World.setBlock(i - 3, j - 2, k - 2, Blocks.air);
        Par2World.setBlock(i - 3, j - 2, k - 3, Blocks.air);
        Par2World.setBlock(i - 2, j - 2, k + 3, Blocks.air);
        Par2World.setBlock(i - 2, j - 2, k + 2, Blocks.air);
        Par2World.setBlock(i - 2, j - 2, k + 1, Blocks.air);
        Par2World.setBlock(i - 2, j - 2, k, Blocks.air);
        Par2World.setBlock(i - 2, j - 2, k - 1, Blocks.air);
        Par2World.setBlock(i - 2, j - 2, k - 2, Blocks.air);
        Par2World.setBlock(i - 2, j - 2, k - 3, Blocks.air);
        Par2World.setBlock(i - 1, j - 2, k + 3, Blocks.air);
        Par2World.setBlock(i - 1, j - 2, k + 2, Blocks.air);
        Par2World.setBlock(i - 1, j - 2, k - 2, Blocks.air);
        Par2World.setBlock(i - 1, j - 2, k - 3, Blocks.air);
        Par2World.setBlock(i, j - 2, k + 3, Blocks.air);
        Par2World.setBlock(i, j - 2, k + 2, Blocks.air);
        Par2World.setBlock(i, j - 2, k - 2, Blocks.air);
        Par2World.setBlock(i, j - 2, k - 3, Blocks.air);
        Par2World.setBlock(i + 1, j - 2, k + 3, Blocks.air);
        Par2World.setBlock(i + 1, j - 2, k + 2, Blocks.air);
        Par2World.setBlock(i + 1, j - 2, k - 2, Blocks.air);
        Par2World.setBlock(i + 1, j - 2, k - 3, Blocks.air);
        Par2World.setBlock(i + 2, j - 2, k + 3, Blocks.air);
        Par2World.setBlock(i + 2, j - 2, k + 2, Blocks.air);
        Par2World.setBlock(i + 2, j - 2, k + 1, Blocks.air);
        Par2World.setBlock(i + 2, j - 2, k, Blocks.air);
        Par2World.setBlock(i + 2, j - 2, k - 1, Blocks.air);
        Par2World.setBlock(i + 2, j - 2, k - 2, Blocks.air);
        Par2World.setBlock(i + 2, j - 2, k - 3, Blocks.air);
        Par2World.setBlock(i + 3, j - 2, k + 3, Blocks.air);
        Par2World.setBlock(i + 3, j - 2, k + 2, Blocks.air);
        Par2World.setBlock(i + 3, j - 2, k + 1, Blocks.air);
        Par2World.setBlock(i + 3, j - 2, k, Blocks.air);
        Par2World.setBlock(i + 3, j - 2, k - 1, Blocks.air);
        Par2World.setBlock(i + 3, j - 2, k - 2, Blocks.air);
        Par2World.setBlock(i + 3, j - 2, k - 3, Blocks.air);
        Par2World.setBlock(i + 4, j - 2, k - 4, Blocks.air);
        Par2World.setBlock(i + 4, j - 2, k - 3, Blocks.air);
        Par2World.setBlock(i + 4, j - 2, k - 2, Blocks.air);
        Par2World.setBlock(i + 4, j - 2, k - 1, Blocks.air);
        Par2World.setBlock(i + 4, j - 2, k, Blocks.air);
        Par2World.setBlock(i + 4, j - 2, k + 1, Blocks.air);
        Par2World.setBlock(i + 4, j - 2, k + 2, Blocks.air);
        Par2World.setBlock(i + 4, j - 2, k + 3, Blocks.air);
        Par2World.setBlock(i + 4, j - 2, k + 4, Blocks.air);
        Par2World.setBlock(i - 4, j - 2, k - 4, Blocks.air);
        Par2World.setBlock(i - 4, j - 2, k - 3, Blocks.air);
        Par2World.setBlock(i - 4, j - 2, k - 2, Blocks.air);
        Par2World.setBlock(i - 4, j - 2, k - 1, Blocks.air);
        Par2World.setBlock(i - 4, j - 2, k, Blocks.air);
        Par2World.setBlock(i - 4, j - 2, k + 1, Blocks.air);
        Par2World.setBlock(i - 4, j - 2, k + 2, Blocks.air);
        Par2World.setBlock(i - 4, j - 2, k + 3, Blocks.air);
        Par2World.setBlock(i - 4, j - 2, k + 4, Blocks.air);
        Par2World.setBlock(i - 3, j - 2, k + 4, Blocks.air);
        Par2World.setBlock(i - 2, j - 2, k + 4, Blocks.air);
        Par2World.setBlock(i - 1, j - 2, k + 4, Blocks.air);
        Par2World.setBlock(i, j - 2, k + 4, Blocks.air);
        Par2World.setBlock(i + 1, j - 2, k + 4, Blocks.air);
        Par2World.setBlock(i + 2, j - 2, k + 4, Blocks.air);
        Par2World.setBlock(i + 3, j - 2, k + 4, Blocks.air);
        Par2World.setBlock(i - 3, j - 2, k - 4, Blocks.air);
        Par2World.setBlock(i - 2, j - 2, k - 4, Blocks.air);
        Par2World.setBlock(i - 1, j - 2, k - 4, Blocks.air);
        Par2World.setBlock(i, j - 2, k - 4, Blocks.air);
        Par2World.setBlock(i + 1, j - 2, k - 4, Blocks.air);
        Par2World.setBlock(i + 2, j - 2, k - 4, Blocks.air);
        Par2World.setBlock(i + 3, j - 2, k - 4, Blocks.air);
        Par2World.setBlock(i + 5, j - 2, k - 5, Blocks.air);
        Par2World.setBlock(i + 5, j - 2, k - 4, Blocks.air);
        Par2World.setBlock(i + 5, j - 2, k - 3, Blocks.air);
        Par2World.setBlock(i + 5, j - 2, k - 2, Blocks.air);
        Par2World.setBlock(i + 5, j - 2, k - 1, Blocks.air);
        Par2World.setBlock(i + 5, j - 2, k, Blocks.air);
        Par2World.setBlock(i + 5, j - 2, k + 1, Blocks.air);
        Par2World.setBlock(i + 5, j - 2, k + 2, Blocks.air);
        Par2World.setBlock(i + 5, j - 2, k + 3, Blocks.air);
        Par2World.setBlock(i + 5, j - 2, k + 4, Blocks.air);
        Par2World.setBlock(i + 5, j - 2, k + 5, Blocks.air);
        Par2World.setBlock(i - 5, j - 2, k - 5, Blocks.air);
        Par2World.setBlock(i - 5, j - 2, k - 4, Blocks.air);
        Par2World.setBlock(i - 5, j - 2, k - 3, Blocks.air);
        Par2World.setBlock(i - 5, j - 2, k - 2, Blocks.air);
        Par2World.setBlock(i - 5, j - 2, k - 1, Blocks.air);
        Par2World.setBlock(i - 5, j - 2, k, Blocks.air);
        Par2World.setBlock(i - 5, j - 2, k + 1, Blocks.air);
        Par2World.setBlock(i - 5, j - 2, k + 2, Blocks.air);
        Par2World.setBlock(i - 5, j - 2, k + 3, Blocks.air);
        Par2World.setBlock(i - 5, j - 2, k + 4, Blocks.air);
        Par2World.setBlock(i - 5, j - 2, k + 5, Blocks.air);
        Par2World.setBlock(i - 4, j - 2, k + 5, Blocks.air);
        Par2World.setBlock(i - 3, j - 2, k + 5, Blocks.air);
        Par2World.setBlock(i - 2, j - 2, k + 5, Blocks.air);
        Par2World.setBlock(i - 1, j - 2, k + 5, Blocks.air);
        Par2World.setBlock(i, j - 2, k + 5, Blocks.air);
        Par2World.setBlock(i + 1, j - 2, k + 5, Blocks.air);
        Par2World.setBlock(i + 2, j - 2, k + 5, Blocks.air);
        Par2World.setBlock(i + 3, j - 2, k + 5, Blocks.air);
        Par2World.setBlock(i - 4, j - 2, k + 5, Blocks.air);
        Par2World.setBlock(i - 4, j - 2, k - 5, Blocks.air);
        Par2World.setBlock(i - 3, j - 2, k - 5, Blocks.air);
        Par2World.setBlock(i - 2, j - 2, k - 5, Blocks.air);
        Par2World.setBlock(i - 1, j - 2, k - 5, Blocks.air);
        Par2World.setBlock(i, j - 2, k - 5, Blocks.air);
        Par2World.setBlock(i + 1, j - 2, k - 5, Blocks.air);
        Par2World.setBlock(i + 2, j - 2, k - 5, Blocks.air);
        Par2World.setBlock(i + 3, j - 2, k - 5, Blocks.air);
        Par2World.setBlock(i - 4, j - 2, k - 5, Blocks.air);
        Par2World.setBlock(i - 3, j + 1, k + 3, (Block)Blocks.sand);
        Par2World.setBlock(i - 3, j + 1, k + 2, (Block)Blocks.sand);
        Par2World.setBlock(i - 3, j + 1, k + 1, (Block)Blocks.sand);
        Par2World.setBlock(i - 3, j + 1, k, (Block)Blocks.sand);
        Par2World.setBlock(i - 3, j + 1, k - 1, (Block)Blocks.sand);
        Par2World.setBlock(i - 3, j + 1, k - 2, (Block)Blocks.sand);
        Par2World.setBlock(i - 3, j + 1, k - 3, (Block)Blocks.sand);
        Par2World.setBlock(i - 2, j + 1, k + 3, (Block)Blocks.sand);
        Par2World.setBlock(i - 2, j + 1, k + 2, (Block)Blocks.sand);
        Par2World.setBlock(i - 2, j + 1, k + 1, (Block)Blocks.sand);
        Par2World.setBlock(i - 2, j + 1, k, (Block)Blocks.sand);
        Par2World.setBlock(i - 2, j + 1, k - 1, (Block)Blocks.sand);
        Par2World.setBlock(i - 2, j + 1, k - 2, (Block)Blocks.sand);
        Par2World.setBlock(i - 2, j + 1, k - 3, (Block)Blocks.sand);
        Par2World.setBlock(i - 1, j + 1, k + 3, (Block)Blocks.sand);
        Par2World.setBlock(i - 1, j + 1, k + 2, (Block)Blocks.sand);
        Par2World.setBlock(i - 1, j + 1, k - 2, (Block)Blocks.sand);
        Par2World.setBlock(i - 1, j + 1, k - 3, (Block)Blocks.sand);
        Par2World.setBlock(i, j + 1, k + 3, (Block)Blocks.sand);
        Par2World.setBlock(i, j + 1, k + 2, (Block)Blocks.sand);
        Par2World.setBlock(i, j + 1, k - 2, (Block)Blocks.sand);
        Par2World.setBlock(i, j + 1, k - 3, (Block)Blocks.sand);
        Par2World.setBlock(i + 1, j + 1, k + 3, (Block)Blocks.sand);
        Par2World.setBlock(i + 1, j + 1, k + 2, (Block)Blocks.sand);
        Par2World.setBlock(i + 1, j + 1, k - 2, (Block)Blocks.sand);
        Par2World.setBlock(i + 1, j + 1, k - 3, (Block)Blocks.sand);
        Par2World.setBlock(i + 2, j + 1, k + 3, (Block)Blocks.sand);
        Par2World.setBlock(i + 2, j + 1, k + 2, (Block)Blocks.sand);
        Par2World.setBlock(i + 2, j + 1, k + 1, (Block)Blocks.sand);
        Par2World.setBlock(i + 2, j + 1, k, (Block)Blocks.sand);
        Par2World.setBlock(i + 2, j + 1, k - 1, (Block)Blocks.sand);
        Par2World.setBlock(i + 2, j + 1, k - 2, (Block)Blocks.sand);
        Par2World.setBlock(i + 2, j + 1, k - 3, (Block)Blocks.sand);
        Par2World.setBlock(i + 3, j + 1, k + 3, (Block)Blocks.sand);
        Par2World.setBlock(i + 3, j + 1, k + 2, (Block)Blocks.sand);
        Par2World.setBlock(i + 3, j + 1, k + 1, (Block)Blocks.sand);
        Par2World.setBlock(i + 3, j + 1, k, (Block)Blocks.sand);
        Par2World.setBlock(i + 3, j + 1, k - 1, (Block)Blocks.sand);
        Par2World.setBlock(i + 3, j + 1, k - 2, (Block)Blocks.sand);
        Par2World.setBlock(i + 3, j + 1, k - 3, (Block)Blocks.sand);
        Par2World.setBlock(i + 4, j + 2, k - 4, (Block)Blocks.sand);
        Par2World.setBlock(i + 4, j + 2, k - 3, (Block)Blocks.sand);
        Par2World.setBlock(i + 4, j + 2, k - 2, (Block)Blocks.sand);
        Par2World.setBlock(i + 4, j + 2, k - 1, (Block)Blocks.sand);
        Par2World.setBlock(i + 4, j + 2, k, (Block)Blocks.sand);
        Par2World.setBlock(i + 4, j + 2, k + 1, (Block)Blocks.sand);
        Par2World.setBlock(i + 4, j + 2, k + 2, (Block)Blocks.sand);
        Par2World.setBlock(i + 4, j + 2, k + 3, (Block)Blocks.sand);
        Par2World.setBlock(i + 4, j + 2, k + 4, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 2, k - 4, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 2, k - 3, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 2, k - 2, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 2, k - 1, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 2, k, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 2, k + 1, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 2, k + 2, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 2, k + 3, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 2, k + 4, (Block)Blocks.sand);
        Par2World.setBlock(i - 3, j + 2, k + 4, (Block)Blocks.sand);
        Par2World.setBlock(i - 2, j + 2, k + 4, (Block)Blocks.sand);
        Par2World.setBlock(i - 1, j + 2, k + 4, (Block)Blocks.sand);
        Par2World.setBlock(i, j + 2, k + 4, (Block)Blocks.sand);
        Par2World.setBlock(i + 1, j + 2, k + 4, (Block)Blocks.sand);
        Par2World.setBlock(i + 2, j + 2, k + 4, (Block)Blocks.sand);
        Par2World.setBlock(i + 3, j + 2, k + 4, (Block)Blocks.sand);
        Par2World.setBlock(i - 3, j + 2, k - 4, (Block)Blocks.sand);
        Par2World.setBlock(i - 2, j + 2, k - 4, (Block)Blocks.sand);
        Par2World.setBlock(i - 1, j + 2, k - 4, (Block)Blocks.sand);
        Par2World.setBlock(i, j + 2, k - 4, (Block)Blocks.sand);
        Par2World.setBlock(i + 1, j + 2, k - 4, (Block)Blocks.sand);
        Par2World.setBlock(i + 2, j + 2, k - 4, (Block)Blocks.sand);
        Par2World.setBlock(i + 3, j + 2, k - 4, (Block)Blocks.sand);
        Par2World.setBlock(i + 5, j + 3, k - 5, (Block)Blocks.sand);
        Par2World.setBlock(i + 5, j + 3, k - 4, (Block)Blocks.sand);
        Par2World.setBlock(i + 5, j + 3, k - 3, (Block)Blocks.sand);
        Par2World.setBlock(i + 5, j + 3, k - 2, (Block)Blocks.sand);
        Par2World.setBlock(i + 5, j + 3, k - 1, (Block)Blocks.sand);
        Par2World.setBlock(i + 5, j + 3, k, (Block)Blocks.sand);
        Par2World.setBlock(i + 5, j + 3, k + 1, (Block)Blocks.sand);
        Par2World.setBlock(i + 5, j + 3, k + 2, (Block)Blocks.sand);
        Par2World.setBlock(i + 5, j + 3, k + 3, (Block)Blocks.sand);
        Par2World.setBlock(i + 5, j + 3, k + 4, (Block)Blocks.sand);
        Par2World.setBlock(i + 5, j + 3, k + 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 5, j + 3, k - 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 5, j + 3, k - 4, (Block)Blocks.sand);
        Par2World.setBlock(i - 5, j + 3, k - 3, (Block)Blocks.sand);
        Par2World.setBlock(i - 5, j + 3, k - 2, (Block)Blocks.sand);
        Par2World.setBlock(i - 5, j + 3, k - 1, (Block)Blocks.sand);
        Par2World.setBlock(i - 5, j + 3, k, (Block)Blocks.sand);
        Par2World.setBlock(i - 5, j + 3, k + 1, (Block)Blocks.sand);
        Par2World.setBlock(i - 5, j + 3, k + 2, (Block)Blocks.sand);
        Par2World.setBlock(i - 5, j + 3, k + 3, (Block)Blocks.sand);
        Par2World.setBlock(i - 5, j + 3, k + 4, (Block)Blocks.sand);
        Par2World.setBlock(i - 5, j + 3, k + 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 3, k + 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 3, j + 3, k + 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 2, j + 3, k + 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 1, j + 3, k + 5, (Block)Blocks.sand);
        Par2World.setBlock(i, j + 3, k + 5, (Block)Blocks.sand);
        Par2World.setBlock(i + 1, j + 3, k + 5, (Block)Blocks.sand);
        Par2World.setBlock(i + 2, j + 3, k + 5, (Block)Blocks.sand);
        Par2World.setBlock(i + 3, j + 3, k + 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 3, k + 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 3, k - 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 3, j + 3, k - 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 2, j + 3, k - 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 1, j + 3, k - 5, (Block)Blocks.sand);
        Par2World.setBlock(i, j + 3, k - 5, (Block)Blocks.sand);
        Par2World.setBlock(i + 1, j + 3, k - 5, (Block)Blocks.sand);
        Par2World.setBlock(i + 2, j + 3, k - 5, (Block)Blocks.sand);
        Par2World.setBlock(i + 3, j + 3, k - 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 3, k - 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 3, j + 2, k + 3, (Block)Blocks.sand);
        Par2World.setBlock(i - 3, j + 2, k + 2, (Block)Blocks.sand);
        Par2World.setBlock(i - 3, j + 2, k + 1, (Block)Blocks.sand);
        Par2World.setBlock(i - 3, j + 2, k, (Block)Blocks.sand);
        Par2World.setBlock(i - 3, j + 2, k - 1, (Block)Blocks.sand);
        Par2World.setBlock(i - 3, j + 2, k - 2, (Block)Blocks.sand);
        Par2World.setBlock(i - 3, j + 2, k - 3, (Block)Blocks.sand);
        Par2World.setBlock(i - 2, j + 2, k + 3, (Block)Blocks.sand);
        Par2World.setBlock(i - 2, j, k + 2, (Block)Blocks.sand);
        Par2World.setBlock(i - 2, j, k + 1, (Block)Blocks.sand);
        Par2World.setBlock(i - 2, j, k, (Block)Blocks.sand);
        Par2World.setBlock(i - 2, j, k - 1, (Block)Blocks.sand);
        Par2World.setBlock(i - 2, j, k - 2, (Block)Blocks.sand);
        Par2World.setBlock(i - 2, j + 2, k - 3, (Block)Blocks.sand);
        Par2World.setBlock(i - 1, j + 2, k + 3, (Block)Blocks.sand);
        Par2World.setBlock(i - 1, j, k + 2, (Block)Blocks.sand);
        Par2World.setBlock(i - 1, j, k - 2, (Block)Blocks.sand);
        Par2World.setBlock(i - 1, j + 2, k - 3, (Block)Blocks.sand);
        Par2World.setBlock(i, j + 2, k + 3, (Block)Blocks.sand);
        Par2World.setBlock(i, j, k + 2, (Block)Blocks.sand);
        Par2World.setBlock(i, j, k - 2, (Block)Blocks.sand);
        Par2World.setBlock(i, j + 2, k - 3, (Block)Blocks.sand);
        Par2World.setBlock(i + 1, j + 2, k + 3, (Block)Blocks.sand);
        Par2World.setBlock(i + 1, j, k + 2, (Block)Blocks.sand);
        Par2World.setBlock(i + 1, j, k - 2, (Block)Blocks.sand);
        Par2World.setBlock(i + 1, j + 2, k - 3, (Block)Blocks.sand);
        Par2World.setBlock(i + 2, j + 2, k + 3, (Block)Blocks.sand);
        Par2World.setBlock(i + 2, j, k + 2, (Block)Blocks.sand);
        Par2World.setBlock(i + 2, j, k + 1, (Block)Blocks.sand);
        Par2World.setBlock(i + 2, j, k, (Block)Blocks.sand);
        Par2World.setBlock(i + 2, j, k - 1, (Block)Blocks.sand);
        Par2World.setBlock(i + 2, j, k - 2, (Block)Blocks.sand);
        Par2World.setBlock(i + 2, j + 2, k - 3, (Block)Blocks.sand);
        Par2World.setBlock(i + 3, j + 2, k + 3, (Block)Blocks.sand);
        Par2World.setBlock(i + 3, j + 2, k + 2, (Block)Blocks.sand);
        Par2World.setBlock(i + 3, j + 2, k + 1, (Block)Blocks.sand);
        Par2World.setBlock(i + 3, j + 2, k, (Block)Blocks.sand);
        Par2World.setBlock(i + 3, j + 2, k - 1, (Block)Blocks.sand);
        Par2World.setBlock(i + 3, j + 2, k - 2, (Block)Blocks.sand);
        Par2World.setBlock(i + 3, j + 2, k - 3, (Block)Blocks.sand);
        Par2World.setBlock(i + 4, j + 3, k - 4, (Block)Blocks.sand);
        Par2World.setBlock(i + 4, j + 3, k - 3, (Block)Blocks.sand);
        Par2World.setBlock(i + 4, j + 3, k - 2, (Block)Blocks.sand);
        Par2World.setBlock(i + 4, j + 3, k - 1, (Block)Blocks.sand);
        Par2World.setBlock(i + 4, j + 3, k, (Block)Blocks.sand);
        Par2World.setBlock(i + 4, j + 3, k + 1, (Block)Blocks.sand);
        Par2World.setBlock(i + 4, j + 3, k + 2, (Block)Blocks.sand);
        Par2World.setBlock(i + 4, j + 3, k + 3, (Block)Blocks.sand);
        Par2World.setBlock(i + 4, j + 3, k + 4, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 3, k - 4, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 3, k - 3, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 3, k - 2, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 3, k - 1, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 3, k, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 3, k + 1, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 3, k + 2, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 3, k + 3, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 3, k + 4, (Block)Blocks.sand);
        Par2World.setBlock(i - 3, j + 3, k + 4, (Block)Blocks.sand);
        Par2World.setBlock(i - 2, j + 3, k + 4, (Block)Blocks.sand);
        Par2World.setBlock(i - 1, j + 3, k + 4, (Block)Blocks.sand);
        Par2World.setBlock(i, j + 3, k + 4, (Block)Blocks.sand);
        Par2World.setBlock(i + 1, j + 3, k + 4, (Block)Blocks.sand);
        Par2World.setBlock(i + 2, j + 3, k + 4, (Block)Blocks.sand);
        Par2World.setBlock(i + 3, j + 3, k + 4, (Block)Blocks.sand);
        Par2World.setBlock(i - 3, j + 3, k - 4, (Block)Blocks.sand);
        Par2World.setBlock(i - 2, j + 3, k - 4, (Block)Blocks.sand);
        Par2World.setBlock(i - 1, j + 3, k - 4, (Block)Blocks.sand);
        Par2World.setBlock(i, j + 3, k - 4, (Block)Blocks.sand);
        Par2World.setBlock(i + 1, j + 3, k - 4, (Block)Blocks.sand);
        Par2World.setBlock(i + 2, j + 3, k - 4, (Block)Blocks.sand);
        Par2World.setBlock(i + 3, j + 3, k - 4, (Block)Blocks.sand);
        Par2World.setBlock(i + 5, j + 4, k - 5, (Block)Blocks.sand);
        Par2World.setBlock(i + 5, j + 4, k - 4, (Block)Blocks.sand);
        Par2World.setBlock(i + 5, j + 4, k - 3, (Block)Blocks.sand);
        Par2World.setBlock(i + 5, j + 4, k - 2, (Block)Blocks.sand);
        Par2World.setBlock(i + 5, j + 4, k - 1, (Block)Blocks.sand);
        Par2World.setBlock(i + 5, j + 4, k, (Block)Blocks.sand);
        Par2World.setBlock(i + 5, j + 4, k + 1, (Block)Blocks.sand);
        Par2World.setBlock(i + 5, j + 4, k + 2, (Block)Blocks.sand);
        Par2World.setBlock(i + 5, j + 4, k + 3, (Block)Blocks.sand);
        Par2World.setBlock(i + 5, j + 4, k + 4, (Block)Blocks.sand);
        Par2World.setBlock(i + 5, j + 4, k + 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 5, j + 4, k - 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 5, j + 4, k - 4, (Block)Blocks.sand);
        Par2World.setBlock(i - 5, j + 4, k - 3, (Block)Blocks.sand);
        Par2World.setBlock(i - 5, j + 4, k - 2, (Block)Blocks.sand);
        Par2World.setBlock(i - 5, j + 4, k - 1, (Block)Blocks.sand);
        Par2World.setBlock(i - 5, j + 4, k, (Block)Blocks.sand);
        Par2World.setBlock(i - 5, j + 4, k + 1, (Block)Blocks.sand);
        Par2World.setBlock(i - 5, j + 4, k + 2, (Block)Blocks.sand);
        Par2World.setBlock(i - 5, j + 4, k + 3, (Block)Blocks.sand);
        Par2World.setBlock(i - 5, j + 4, k + 4, (Block)Blocks.sand);
        Par2World.setBlock(i - 5, j + 4, k + 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 4, k + 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 3, j + 4, k + 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 2, j + 4, k + 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 1, j + 4, k + 5, (Block)Blocks.sand);
        Par2World.setBlock(i, j + 4, k + 5, (Block)Blocks.sand);
        Par2World.setBlock(i + 1, j + 4, k + 5, (Block)Blocks.sand);
        Par2World.setBlock(i + 2, j + 4, k + 5, (Block)Blocks.sand);
        Par2World.setBlock(i + 3, j + 4, k + 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 4, k + 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 4, k - 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 3, j + 4, k - 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 2, j + 4, k - 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 1, j + 4, k - 5, (Block)Blocks.sand);
        Par2World.setBlock(i, j + 4, k - 5, (Block)Blocks.sand);
        Par2World.setBlock(i + 1, j + 4, k - 5, (Block)Blocks.sand);
        Par2World.setBlock(i + 2, j + 4, k - 5, (Block)Blocks.sand);
        Par2World.setBlock(i + 3, j + 4, k - 5, (Block)Blocks.sand);
        Par2World.setBlock(i - 4, j + 4, k - 5, (Block)Blocks.sand);
        Par3EntityPlayer.addChatComponentMessage((IChatComponent)new ChatComponentText("Sand Tsunami!!"));
        props.consumeMana(25 + props.getNinjutsu() / 600);
      } else {
        Par3EntityPlayer.addChatComponentMessage((IChatComponent)new ChatComponentText("You do not have enough chakra"));
      } 
    } 
    return Par1ItemStack;
  }
  
  @SideOnly(Side.CLIENT)
  public void addInformation(ItemStack par1ItemStack, EntityPlayer par2EntityPlayer, List par3List, boolean par4) {
    ExtendedPlayer props = ExtendedPlayer.get(par2EntityPlayer);
    if (par1ItemStack.stackTagCompound != null)
      par3List.add(EnumChatFormatting.AQUA + "Owner: " + par1ItemStack.stackTagCompound.getString("Owner")); 
    par3List.add(EnumChatFormatting.DARK_AQUA + "Creates a tsunami around the user");
    par3List.add(EnumChatFormatting.DARK_AQUA + "burrowing anyone close by");
    par3List.add(EnumChatFormatting.GOLD + "Chakra Cost: " + (25 + props.getNinjutsu() / 600));
    par3List.add(EnumChatFormatting.DARK_RED + "Damage: " + (6 + props.getNinjutsu() / 600));
  }
}
